export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS'
export const LOAD_LIST_FAILURE = 'LOAD_LIST_FAILURE'

export const LOAD_COM_SUCCESS = 'LOAD_COM_SUCCESS'
export const LOAD_COM_FAILURE = 'LOAD_COM_FAILURE'